# .travis.yml
language: node_js

sudo: false

node_js:
  - '0.10'
  - '0.12'
  - '4'
  - '5'

before_script:
  - psql -c 'create database atlas_test;' -U postgres

notifications:
  email: false

matrix:
  fast_finish: true
